# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./mvnw -Drat.skip=true
  displayName: 'Run mvwm'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls -al "/home/vsts/work/1/s"
  displayName: 'Run a multi-line script'

- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'IQServer'
    applicationId: 'struts2-rce'
    stage: '$IQ-STAGE'